/* src\Views\AutoComplete.svelte generated by Svelte v3.31.2 */
import {
	SvelteComponent,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	noop,
	safe_not_equal,
	transition_in,
	transition_out
} from "../../_snowpack/pkg/svelte/internal.js";

import TextInput from "../Components/Forms/TextInput.svelte.js";

function create_fragment(ctx) {
	let div;
	let textinput;
	let current;
	textinput = new TextInput({});

	return {
		c() {
			div = element("div");
			create_component(textinput.$$.fragment);
		},
		m(target, anchor) {
			insert(target, div, anchor);
			mount_component(textinput, div, null);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(textinput.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(textinput.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div);
			destroy_component(textinput);
		}
	};
}

class AutoComplete extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default AutoComplete;