/* src\Components\Forms\TextInput.svelte generated by Svelte v3.31.2 */
import {
	SvelteComponent,
	action_destroyer,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "../../../_snowpack/pkg/svelte/internal.js";

import { suggestions } from "../../Actions/AutoComplete/suggestions.js";

function create_fragment(ctx) {
	let input;
	let suggestions_action;
	let mounted;
	let dispose;

	return {
		c() {
			input = element("input");
			attr(input, "type", "text");
		},
		m(target, anchor) {
			insert(target, input, anchor);

			if (!mounted) {
				dispose = action_destroyer(suggestions_action = suggestions.call(null, input));
				mounted = true;
			}
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(input);
			mounted = false;
			dispose();
		}
	};
}

class TextInput extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default TextInput;